import { FormSessionDetails } from '@/types/database'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import { createElement } from 'react'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  section: {
    marginTop: 20,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  field: {
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 3,
    color: '#555',
  },
  fieldValue: {
    fontSize: 12,
    color: '#000',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#999',
    borderTop: '1pt solid #ccc',
    paddingTop: 10,
  },
})

export async function generateFormPDF(
  sessionData: FormSessionDetails,
  generatedBy: string
): Promise<Buffer> {
  const valuesByKey = new Map(
    sessionData.values.map((v) => [v.field_key, v])
  )

  const PDFDocument = createElement(Document, {}, [
    createElement(Page, { style: styles.page, key: 'page1' }, [
      // Header
      createElement(View, { style: styles.header, key: 'header' }, [
        createElement(
          Text,
          { style: styles.title, key: 'title' },
          sessionData.template.name
        ),
        createElement(
          Text,
          { style: styles.subtitle, key: 'desc' },
          sessionData.template.description || ''
        ),
        createElement(
          Text,
          { style: styles.subtitle, key: 'date' },
          `Generated: ${new Date().toLocaleString()}`
        ),
      ]),

      // Sections and Fields
      ...sessionData.template.schema.sections.map((section, sIdx) =>
        createElement(View, { style: styles.section, key: `section-${sIdx}` }, [
          createElement(
            Text,
            { style: styles.sectionTitle, key: 'stitle' },
            section.section_name
          ),
          ...section.fields.map((field, fIdx) => {
            const value = valuesByKey.get(field.field_key)
            return createElement(
              View,
              { style: styles.field, key: `field-${fIdx}` },
              [
                createElement(
                  Text,
                  { style: styles.fieldLabel, key: 'label' },
                  field.label
                ),
                createElement(
                  Text,
                  { style: styles.fieldValue, key: 'value' },
                  value?.value_normalized?.toString() || 'N/A'
                ),
              ]
            )
          }),
        ])
      ),

      // Footer
      createElement(
        View,
        { style: styles.footer, key: 'footer' },
        createElement(
          Text,
          null,
          `Generated by ${generatedBy} using VoicedForm`
        )
      ),
    ]),
  ])

  const blob = await pdf(PDFDocument).toBlob()
  return Buffer.from(await blob.arrayBuffer())
}
